on: [push, pull_request, workflow_dispatch]

jobs:
  test1:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          apt update -y && apt install -y git
          pwd
          ls -la
          echo "Hello world" > test.txt
          git config --global user.name bot
          git config --global user.email bot@bot.bot
          git add test.txt
          git commit -m "test2"
          git push
