on: [push, pull_request, workflow_dispatch]
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          sleep 120
          echo "Hello world"
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -lah
