on: [push, pull_request, workflow_dispatch]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/github-script@v7
        id: script1
        with:
          script: |
            cat ./sudoku/main.py && pwd
      - run: |
          cat ./sudoku/main.py && pwd
